### PR TITLE
fix: display `taglist` disabled state properly

### LINKED ISSUE #496: Disabled `taglist` fields do not show imported values
__Describe the Bug__

When specifying input data for a disabled `taglist` field, the viewer does not show the values, but instead only the placeholder.

image

image

This is inconsistent with other fields, where we still display the value while disabled. 

image

__Steps to Reproduce__

1. Create a `taglist`
2. Specify input data for that `taglist`
3. Disable the `taglist`
4. See no values are shown

__Expected Behavior__

Like for other fields, the `taglist` values should be shown also in `disabled` mode.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 108
- OS: macOS
- Library version: 0.10.1

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #496

### CODE REVIEW

**Comment by Skaiir** [comment]
firefox_dThAQ7E3ZE

File: packages/form-js-viewer/src/render/components/form-fields/Taglist.js [hunk 1]
```diff
@@ -128,22 +128,22 @@ export default function Taglist(props) {
...
       id={ prefixId(`${id}-search`, formId) } />
     <div class={ classNames('fjs-taglist', { 'disabled': disabled }) }>
-      {!disabled && loadState === LOAD_STATES.LOADED &&
+      { loadState === LOAD_STATES.LOADED &&
         <div class="fjs-taglist-tags">
           {
             values.map((v) => {
               return (
-                <div class="fjs-taglist-tag" onMouseDown={ (e) => e.preventDefault() }>
+                <div class={ classNames('fjs-taglist-tag', { 'disabled': disabled }) } onMouseDown={ (e) => e.preventDefault() }>
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Taglist.js:136]:
```suggestion
                <div class={ classNames('fjs-taglist-tag', { disabled }) } onMouseDown={ (e) => e.preventDefault() }>
```

File: packages/form-js-viewer/src/render/components/form-fields/Taglist.js [hunk 2]
```diff
@@ -128,22 +128,22 @@ export default function Taglist(props) {
...
                   <span class="fjs-taglist-tag-label">
                     {valueToOptionMap[v] ? valueToOptionMap[v].label : `unexpected value{${v}}`}
                   </span>
-                  <button
+                  { !disabled && <button
                     type="button"
                     title="Remove tag"
-                    class="fjs-taglist-tag-remove"
+                    class={ 'fjs-taglist-tag-remove' }
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Taglist.js:143]:
```suggestion
                    class="fjs-taglist-tag-remove"
```

File: packages/form-js-viewer/assets/form-js.css [hunk 3]
```diff
@@ -483,6 +487,10 @@
   padding: 2px 6px 2px 8px;
 }
 
+.fjs-container .fjs-taglist .fjs-taglist-tag.disabled .fjs-taglist-tag-label {
+  padding: 2px 8px 2px 8px;
```
Comment (vsgoulart) [inline packages/form-js-viewer/assets/form-js.css:491]: Can be shortened a bit

```suggestion
  padding: 2px 8px;
```

**Review by vsgoulart — COMMENTED** [review]
When I change the taglist selected values manually and then disable it, the taglist value resets to the initial value.
Is this expected?

**Comment by Skaiir** [comment]
@vsgoulart Yeah it's expected, the form re-imports the initial state whenever settings changes are made.

File: packages/form-js-viewer/src/render/components/form-fields/Taglist.js (hunk 1 above)
Comment (Skaiir) [reply packages/form-js-viewer/src/render/components/form-fields/Taglist.js:136]: This one I won't simplify as it would break if we ever renamed disabled. 

One disabled describes the css class while the other describes the condition for which it should be enabled. The fact that they are the same might change in the future, so for semantic and future-proofing reasons let's keep it this way.

Comment (Skaiir) [reply packages/form-js-viewer/src/render/components/form-fields/Taglist.js:136]: Well okay unlikely to change, but still I think it's good practice to decouple them.

Comment (vsgoulart) [reply packages/form-js-viewer/src/render/components/form-fields/Taglist.js:136]: I think it's not really necessary to separate but ok :sweat_smile: 

but one other thing related this. Shouldn't prefix the class name with `fjs-`

**Review by vsgoulart — APPROVED** [review]

**Comment by Skaiir** [comment]
@vsgoulart You're right the fjs- prefix will make this safer. I'll include it and merge.
