### PR TITLE
fix: properly handle all formats of options sources

### LINKED ISSUE #960: Dynamic options aren't reliable
**What should we do?**

We should ensure that dynamic options for all select-like components work as documented (see https://docs.camunda.io/docs/components/modeler/forms/configuration/forms-config-options/)

That means that values should be able to be defined as objects, for example. 

**Why should we do it?**

Because it's the original behavior. 

See https://app.incident.io/camunda/incidents/798 && https://jira.camunda.com/browse/SUPPORT-19807 for details

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #960

### CODE REVIEW

File: packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+import { isObject } from 'min-dash';
+
+/**
+ * This hook allows us to retrieve the label from a value in linear time by caching it in a map
+ * @param {Array} options
+ */
+export function useLabelCorrelation(options) {
+
+  // This allows us to retrieve the label from a value in linear time
+  const labelMap = useMemo(() => Object.assign({}, ...options.map((o) => ({ [_getValueHash(o.value)]:  o.label }))), [ options ]);
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js:11]: Did you have any performance issues? It's not a good idea to abuse `useMemo`,`useCallback`, etc because of memory leaks

File: packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
+import { useCallback, useMemo } from 'preact/hooks';
+import { isObject } from 'min-dash';
+
+/**
+ * This hook allows us to retrieve the label from a value in linear time by caching it in a map
+ * @param {Array} options
+ */
+export function useLabelCorrelation(options) {
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js:8]:
```suggestion
export function useGetLabelCorrelation(options) {
```

File: packages/form-js-viewer/src/render/components/form-fields/Taglist.js [hunk 3]
```diff
@@ -64,8 +66,7 @@ export default function Taglist(props) {
     onChange: props.onChange
   });
 
-  // We cache a map of option values to their index so that we don't need to search the whole options array every time to correlate the label
-  const valueToOptionMap = useMemo(() => Object.assign({}, ...options.map((o, x) => ({ [o.value]:  options[x] }))), [ options ]);
+  const correlateLabel = useLabelCorrelation(options);
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Taglist.js:69]:
```suggestion
  const getLabelCorrelation = useLabelCorrelation(options);
```

File: packages/form-js-viewer/src/render/components/util/sanitizerUtil.js [hunk 4]
```diff
@@ -19,6 +20,15 @@ export function sanitizeDateTimePickerValue(options) {
   return value;
 }
 
+export function isDeepIncluded(value, array) {
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/util/sanitizerUtil.js:23]: The name is not very descriptive, I think we can improve it

```suggestion
export function hasEqualValue(value, array) {
```

File: packages/form-js-viewer/src/render/components/form-fields/Radio.js [hunk 5]
```diff
@@ -1,4 +1,5 @@
 import { useRef } from 'preact/hooks';
+import isDeepEqual from 'lodash/isEqual';
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Radio.js:2]: Let's not rename it unless it's necessary

```suggestion
import isEqual from 'lodash/isEqual';
```

**Review by vsgoulart — COMMENTED** [review]
It worked fine while testing, I have some minor comments though

File: packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js (hunk 1 above)
Comment (Skaiir) [reply packages/form-js-viewer/src/render/hooks/useLabelCorrelation.js:11]: Yeah, this is why it's here and it's always been that way. I've just brought this pattern into a hook because we use it a few places. Otherwise the complexity is n^2 and we want the components to deal with values of n > 1000
