### PR TITLE
Accessible select component

### LINKED ISSUE #617: Label of `select` field does not properly reference
### Describe the Bug

_This was reported via https://github.com/camunda/team-hto/issues/214._

The label of a `select` field does not properly reference. This leads that clicking the label does not properly focus element. Also, screen readers might have problems to properly connect label and element

image

### Steps to Reproduce

1. Create a `select`
2. Add a label
3. Execute a11y checker as [IBM Equal Access Accessibility Checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp)
4. See error popping up, e.g. `The value "fjs-form-05oenrj-Field_00trkfo" of the 'for' attribute is not the 'id' of a valid element`

### Expected Behavior

The label of the custom `select` is properly linked to the element.

### Environment

- Host (Browser/Node version), if applicable: Chrome 112.0.5615.49
- OS: macOS 13.2.1
- Library version: `master`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #617 

Make sure a non-searchable select's label is properly bound to an input field. This was an issue reported via https://github.com/camunda/team-hto/issues/214

Kapture 2023-04-21 at 10 22 17

### CODE REVIEW

File: packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js [hunk 1]
```diff
@@ -73,9 +73,15 @@ export default function SimpleSelect(props) {
       class={ classNames('fjs-input-group', { 'disabled': disabled }, { 'hasErrors': errors.length }) }
       onFocus={ () => setIsDropdownExpanded(true) }
       onBlur={ () => setIsDropdownExpanded(false) }
-      onMouseDown={ (e) => onMouseDown(e) }
-      tabIndex={ disabled ? undefined : 0 }>
+      onMouseDown={ (e) => onMouseDown(e) }>
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js:76]:
```suggestion
      onMouseDown={ onMouseDown }>
```

**Review by vsgoulart — APPROVED** [review]
