### PR TITLE
fix: make expression result evaluation more reliable

### LINKED ISSUE #1114: Expression results get wiped during form editing
### Describe the Bug

Expression results are not recalculated every time when moving form elements around in the editor, see the [modeler issue](https://github.com/camunda/camunda-modeler/issues/4227) for details.

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #1114

### CODE REVIEW

File: packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js [hunk 1]
```diff
@@ -1,12 +1,13 @@
 import { useCallback, useEffect } from 'preact/hooks';
-import { useExpressionEvaluation, useDeepCompareMemoize, useService, useEffectOnChange } from '../../hooks';
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js:2]: `useEffectOnChange` is not used anymore, let's delete it

Comment (Skaiir) [reply packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js:2]: Nicely spotted, removed it :)

**Review by vsgoulart — APPROVED** [review]

**Comment by barmac** [comment]
Hi, I noticed that this PR doesn't contain any tests. How do we verify that the feature doesn't break again?
