### PR TITLE
Datetime: correct `autocomplete` attribute

### LINKED ISSUE #522: Date time fields use an invalid `autocomplete` attribute
### Describe the Bug

Using the [IBM Equal access checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp) it throws an error for a form with date time fields.

> The 'autocomplete' attribute has an incorrect value

```html
<input
    data-input="true"
    autocomplete="false"
    placeholder="mm/dd/yyyy"
    class="fjs-input flatpickr-input"
    id="fjs-form-0nl2jhz-datetime1--date"
    type="text">
```

### Steps to Reproduce

1. Create a form with a date, time or date time field
2. Evaluate a11y via [IBM Equal access checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp) 
3. See error reported

### Expected Behavior

The date time fields should have a valid `autocomplete` attribute value. 

> autocomplete="off"

Cf. https://www.w3schools.com/tags/att_input_autocomplete.asp

### Environment

- Host (Browser/Node version), if applicable: Chrome 109
- OS: macOS 12.6
- Library version: `master`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #522 

Apparently, we didn't test against the [`autocomplete-valid`](https://dequeuniversity.com/rules/axe/4.6/autocomplete-valid?application=RuleDescription) rule beforehand, as it was not part of the used test definitions. 

I added `cat.forms` to cover this; it makes anyway sense to use these best practices.

### CODE REVIEW

File: packages/form-js-viewer/test/TestHelper.js [hunk 1]
```diff
@@ -5,6 +5,9 @@ import { insertCSS } from './helper';
 // @ts-ignore-next-line
 import formCSS from '../dist/assets/form-js.css';
 
+// @ts-ignore-next-line
+import flatpickrCSS from '@bpmn-io/form-js-viewer/dist/assets/flatpickr/light.css';
```
Comment (vsgoulart) [inline packages/form-js-viewer/test/TestHelper.js:9]: Is this only for tests? Was it already included in the actual implementation?

**Review by vsgoulart — APPROVED** [review]

File: packages/form-js-viewer/test/TestHelper.js (hunk 1 above)
Comment (pinussilvestrus) [reply packages/form-js-viewer/test/TestHelper.js:9]: This is only for tests, yes. We forgot this one for our test suite, as it does not make a big difference for the `npm run start:viewer` test, only visually. I recognized it while inspecting the viewer test in the browser.

**Review by Skaiir — APPROVED** [review]

File: packages/form-js-viewer/test/TestHelper.js (hunk 1 above)
Comment (vsgoulart) [reply packages/form-js-viewer/test/TestHelper.js:9]: Yeah, if this changed anything for the actual implementation we would have to check if it doesn't break the customization on Tasklist
