### PR TITLE
fix: ensure dynamic list and tables interact safely

### LINKED ISSUE #1064: Breaking interaction between dynamic lists and tables
### Describe the Bug

This form apparently breaks form-js

```
{
  "components": [
    {
      "label": "Table",
      "type": "table",
      "layout": {
        "row": "Row_191hb77",
        "columns": null
      },
      "dataSource": "=Field_0r3jms4",
      "rowCount": 3,
      "id": "Field_0r3jms4",
      "columns": [
        {
          "label": "ID",
          "key": "id"
        },
        {
          "label": "Name",
          "key": "name"
        },
        {
          "label": "Date",
          "key": "date"
        }
      ]
    },
    {
      "label": "Number",
      "type": "number",
      "layout": {
        "row": "Row_0dbmu1z",
        "columns": null
      },
      "id": "Field_0fsxs1b",
      "key": "idfilter",
      "defaultValue": 2
    },
    {
      "components": [
        {
          "components": [
            {
              "text": "{{this.id}}",
              "label": "Text view",
              "type": "text",
              "layout": {
                "row": "Row_06z1kim",
                "columns": null
              },
              "id": "Field_0kypubr"
            },
            {
              "label": "Number",
              "type": "number",
              "layout": {
                "row": "Row_0dx6ob8",
                "columns": null
              },
              "id": "Field_0kzopb8",
              "key": "id"
            },
            {
              "label": "Text field",
              "type": "textfield",
              "layout": {
                "row": "Row_1el0dpw",
                "columns": null
              },
              "id": "Field_1jpezr9",
              "key": "name"
            },
            {
              "label": "Text field",
              "type": "textfield",
              "layout": {
                "row": "Row_0sr7lrz",
                "columns": null
              },
              "id": "Field_0ahpidx",
              "key": "date"
            }
          ],
          "showOutline": true,
          "label": "Group",
          "type": "group",
          "layout": {
            "row": "Row_1dr2rq5",
            "columns": null
          },
          "id": "Field_1s20g9l",
          "conditional": {
            "hide": "=this.id < idfilter"
          }
        },
        {
          "label": "Separator",
          "type": "separator",
          "layout": {
            "row": "Row_1q2u5mi",
            "columns": null
          },
          "id": "Field_1uzwox6"
        }
      ],
      "showOutline": true,
      "isRepeating": true,
      "allowAddRemove": true,
      "defaultRepetitions": 1,
      "label": "Dynamic list",
      "type": "dynamiclist",
      "layout": {
        "row": "Row_1w1xmo6",
        "columns": null
      },
      "id": "Field_0596cy3",
      "path": "Field_0r3jms4",
      "nonCollapsedItems": null
    }
  ],
  "type": "default",
  "id": "Form_1je5j4d",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.4.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.20.0"
  },
  "schemaVersion": 15
}
```

### Steps to Reproduce

- Load the following form into the playground

### Expected Behavior

- Form should load without error

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #1064

### CODE REVIEW

File: packages/form-js-viewer/src/render/components/form-fields/Table.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ export function Table(props) {
   );
   const columnKeys = evaluatedColumns.map(({ key }) => key);
   const evaluatedDataSource = useExpressionEvaluation(dataSource);
-  const data = Array.isArray(evaluatedDataSource) ? evaluatedDataSource : [];
+  const data = Array.isArray(evaluatedDataSource) ? evaluatedDataSource.filter(i => i) : [];
```
Comment (douglasbouttell-camunda) [inline packages/form-js-viewer/src/render/components/form-fields/Table.js:59]: Do you want to filter out all [falsy values](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)? Like 0, false, empty string, etc?

Comment (Skaiir) [reply packages/form-js-viewer/src/render/components/form-fields/Table.js:59]: In this case the expected type is object, but you're right it's more logical to filter by undefined (actually our target is <empty>, but undefined will filter for that as well). Made the change.

**Review by vsgoulart — APPROVED** [review]
