### PR TITLE
fix: prevent table component from breaking with invalid data

### LINKED ISSUE #1337: Invalid table data breaks `form-js` in editor mode
### Describe the Bug

When providing a table component data source with a valid FEEL expression that returns invalid data the table component breaks which makes the modeler freeze

### Steps to Reproduce

1. Create an expression field to access the data
2. Try to access this data with a FEEL expression in the table component data source
3. The component breaks and the modeler is frozen

### Expected Behavior

No error should be thrown and the modeler should not freeze

capture hfeojP_optimized

### PR DESCRIPTION
**Pull request by vsgoulart**
This filters out invalid data from the table component which would make it break the entire editor if it happened.

Closes #1337

- [ ] This PR adds a new `form-js` element or visually changes an existing component.
  - => In that case, we need to ensure we follow up on this, e.g. by [creating an issue in Tasklist](https://github.com/camunda/tasklist/issues/new/choose)

### CODE REVIEW

File: packages/form-js-viewer/src/render/components/form-fields/Table.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ export function Table(props) {
   const evaluatedColumns = useEvaluatedColumns(columnsExpression || '', columns);
   const columnKeys = evaluatedColumns.map(({ key }) => key);
   const evaluatedDataSource = useExpressionEvaluation(dataSource);
-  const data = Array.isArray(evaluatedDataSource) ? evaluatedDataSource.filter((i) => i !== undefined) : [];
+  const data = Array.isArray(evaluatedDataSource) ? evaluatedDataSource.filter((entry) => !isNil(entry)) : [];
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Table.js:48]: I couldn't really find a way to test this. Karma didn't throw any errors and it would render an empty table.

If you have any ideas let me know.

File: packages/form-js-viewer/src/render/components/form-fields/Table.js [hunk 2]
```diff
@@ -45,7 +45,9 @@ export function Table(props) {
   const evaluatedColumns = useEvaluatedColumns(columnsExpression || '', columns);
   const columnKeys = evaluatedColumns.map(({ key }) => key);
   const evaluatedDataSource = useExpressionEvaluation(dataSource);
-  const data = Array.isArray(evaluatedDataSource) ? evaluatedDataSource.filter((i) => i !== undefined) : [];
+  const data = Array.isArray(evaluatedDataSource)
```
Comment (vsgoulart) [inline packages/form-js-viewer/src/render/components/form-fields/Table.js:48]: I couldn't really find a way to test this. Karma didn't throw any errors and it would render an empty table.

If you have any ideas let me know.

**Review by Skaiir — APPROVED** [review]
