### PR TITLE
fix(editor): pass correct props to checkbox

### LINKED ISSUE #52: Required Checkbox Not Working
__Describe the Bug__

The _Required_ checkbox in the properties panel isn't working. It's never checked.

https://user-images.githubusercontent.com/7633572/114202766-ccac9900-9957-11eb-9a59-684d7cf341d4.mov

__Environment__

- Library version: 0.0.11

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #52

Related to https://github.com/camunda/camunda-modeler/pull/2205.

### CODE REVIEW

**Review by MaxTru — APPROVED** [review]
Tested in the editor, works

File: packages/form-js-editor/src/rendering/PropertiesPanel.js [hunk 1]
```diff
@@ -172,11 +172,11 @@ function CheckboxEntry(props) {
     }
   };
 
-  const checked = useMemo(() => get(field, path, false), [ get(field, path, false) ]);
+  const value = useMemo(() => get(field, path, false), [ get(field, path, false) ]);
```
Comment (barmac) [inline packages/form-js-editor/src/rendering/PropertiesPanel.js:175]: Outside of the scope of the PR, but I don't get why we use useMemo here 🤡
