### PR TITLE
Do Not Submit Disabled Form or Form Fields

### LINKED ISSUE #6: Do not submit data for disabled fields
__Describe the Bug__

Only values for form elements that are enabled should be submitted with the form. This is standard in web development.

__Steps to Reproduce__

```javascript
import { createForm } from 'camunda-forms';

const schema = {
  "components": [
    {
      "label": "Creditor",
      "key": "creditor",
      "type": "textfield",
      "disabled": true
    }
  ]
};

const form = createForm({
  container: document.createElement('div')
  schema,
  data: { 
    creditor: 'Lisa'
  }
});
```

__Expected Behavior__

```javascript
const {
  data
} = form.submit();

expect(Object.keys(data)).to.be.empty;
```

__Environment__

Any.

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #6

### CODE REVIEW

File: packages/form-js-viewer/src/Form.js [hunk 1]
```diff
@@ -175,12 +175,12 @@ export default class Form {
 
       const fieldErrors = validator.validateField(field, value);
 
-      return set(errors, path, fieldErrors.length ? fieldErrors : undefined);
+      return set(errors, [ pathStringify(path) ], fieldErrors.length ? fieldErrors : undefined);
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:197]: How is this related to the validate fix?

Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js]: The reason using `path` instead of `[ pathStringify(path) ]` works is that we don't support nesting at the moment. Once we add support for nesting it would break as it would create nested objects instead of something like `documents.0.author: [ ... ]` as defined in the `@typedef` of `Errors`.

File: packages/form-js-viewer/src/Form.js [hunk 2]
```diff
@@ -17,7 +17,7 @@ import core from './core';
  * @typedef { import('didi').Injector } Injector
  *
  * @typedef { { [x: string]: any } } Data
- * @typedef { { [x: string]: string[] } } Errors
+ * @typedef { { [x: string]: any } } Errors
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:20]: What is the use-case for this one? What does _any_ represent?

File: packages/form-js-viewer/src/Form.js [hunk 3]
```diff
@@ -158,7 +177,7 @@ export default class Form {
   }
 
   /**
-   * @returns { { [x: string]: string[] } }
+   * @returns {Errors}
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:180]: Is this a breaking change? Or rather a refinement of the existing types? If it is a refinement, we should use it in other places, i.e. [here](https://github.com/bpmn-io/form-js/pull/85/files#diff-53d9b079c7db646b79736d7ab07cd7d3108049b780d14637f41c188a4f6ffc03R20), too.

File: packages/form-js-viewer/src/Form.js [hunk 4]
```diff
@@ -130,12 +130,31 @@ export default class Form {
...
    */
   submit() {
-    this.validate();
+    const { properties = {} } = this._getState();
 
-    const {
-      data,
-      errors
-    } = this._getState();
+    const { readOnly } = properties;
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:135]: We could actually argue that if `properties.readOnly` is set an error should be thrown. 

How can a user submit a read-only marked form? What would be the use-case?

File: packages/form-js-viewer/test/spec/Form.spec.js [hunk 5]
```diff
@@ -117,6 +118,62 @@ describe('createForm', function() {
...
+      container,
+      data,
+      schema,
+      properties: {
+        readOnly: true
+      }
+    });
+
+    // when
+    const submission = form.submit();
```
Comment (nikku) [inline packages/form-js-viewer/test/spec/Form.spec.js:143]: Here I'd expect an error to be thrown :arrow_up:.

**Review by nikku — CHANGES_REQUESTED** [review]
Good work. Some minor remarks inlined.

File: packages/form-js-viewer/src/Form.js (hunk 2 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:20]: TypeScript started complaining after I changed the code of `submit`. This was the error message: 
image

File: packages/form-js-viewer/src/Form.js (hunk 3 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:180]: We simply didn't use the existing `Errors` type here.

File: packages/form-js-viewer/src/Form.js (hunk 4 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:135]: No use case. My idea was that disabled form fields are missing in `data` and that submitting a disabled form would mean that all form fields would be missing in `data`. We could, on the other hand, throw an error, yes.

File: packages/form-js-viewer/src/Form.js (hunk 2 above)
Comment (nikku) [reply packages/form-js-viewer/src/Form.js:20]: Please revert this change and I'll figure it out.

Likely we simply need to change the signature of `set` or manually cast.

File: packages/form-js-viewer/src/Form.js (hunk 4 above)
Comment (nikku) [reply packages/form-js-viewer/src/Form.js:135]: I'd rather throw an error. Submitting a programmatically disabled form is a miss-use of the API that we should indicate.

File: packages/form-js-viewer/src/Form.js (hunk 2 above)
Comment (nikku) [reply packages/form-js-viewer/src/Form.js:20]: Looking into this right now.

File: packages/form-js-viewer/src/Form.js (hunk 4 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:135]: Okay, agreed.

File: packages/form-js-viewer/test/spec/Form.spec.js (hunk 5 above)
Comment (philippfromme) [reply packages/form-js-viewer/test/spec/Form.spec.js]: Done (cf. https://github.com/bpmn-io/form-js/pull/85/files#diff-53d9b079c7db646b79736d7ab07cd7d3108049b780d14637f41c188a4f6ffc03R138).

File: packages/form-js-viewer/src/Form.js (hunk 4 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:135]: Done (cf. https://github.com/bpmn-io/form-js/pull/85/files#diff-53d9b079c7db646b79736d7ab07cd7d3108049b780d14637f41c188a4f6ffc03R138).

File: packages/form-js-viewer/src/Form.js (hunk 2 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js]: The error doesn't appear after I changed the code to throw an error on submitting a read-only form.

File: packages/form-js-viewer/src/Form.js [hunk 6]
```diff
@@ -130,12 +130,30 @@ export default class Form {
...
+
+    if (readOnly) {
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:137]: Any reason we do not use the built-in `#validate` thing? Should `submit` and `validate` exibit different behaviors?

**Review by nikku — COMMENTED** [review]
Sorry... Another remark. Maybe the last one :thinking:

File: packages/form-js-viewer/src/Form.js (hunk 6 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:137]: You mean calling `validate` with some form fields or the entire form disabled?

Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:137]: Should `submit`, `reset` and `validate` all throw an error if the form is disabled?

Comment (nikku) [reply packages/form-js-viewer/src/Form.js:137]: Calling it with some fields disabled. Why don't we re-use that. What is the idea/use-case behind it. Maybe there exists one :)

**Comment by nikku** [comment]
Proposal to simplify the readonly submission error https://github.com/bpmn-io/form-js/pull/85/commits/36f76b62454afebeef46e05a7ba28b3f0e13b8af

File: packages/form-js-viewer/src/Form.js (hunk 6 above)
Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:137]: Yeah, good point. So calling `validate` with `textfield1` disabled shouldn't return errors for that form field, right?

Comment (nikku) [reply packages/form-js-viewer/src/Form.js:137]: Validate and reset do not cause side-effects beyond the form so I'd argue no.

Submit however does (hooking up to submit is the way to trigger external submission). So I'd argue: Submit is guarded while the others are not,.

Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:137]: Okay, will change that.

Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:137]: Okay, so the change would be that `validate` filters disabled form fields and `submit` uses `validate` to get the errors.

Comment (nikku) [reply packages/form-js-viewer/src/Form.js:137]: Exactly.

Comment (philippfromme) [reply packages/form-js-viewer/src/Form.js:139]: Done (cf. https://github.com/bpmn-io/form-js/pull/85/commits/673e7b8a24822c4d1a3c4fb53c4546cccbd53022).

**Comment by nikku** [comment]
Added a minor further simplification: https://github.com/bpmn-io/form-js/pull/85/commits/171279c304d4f978c5858ffa8dde01b18d69df9e

**Review by nikku — APPROVED** [review]
Great! I do believe we have a substantial improvement at our hand here :clap:
