### PR TITLE
fix: properly pass `this` variable context to dynamic list elems

### LINKED ISSUE #1085: Incorrect assignment of the `this` variable in dynamic lists
### Describe the Bug

The this variable in dynamic lists is assigned to the root of a dynamic list, but it should be set to the actually individual data item. 

### Steps to Reproduce

1. create a dynamic list
2. give it a textfield bound to key `variable1`
3. define a text view with feel expression `=this.variable1`
4. set textfield to `"A"`
5. text view shows `"[A]"`

### Expected Behavior

5. text view should show `A`

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #1085

Issue was that restProps also had "value" passed from outer elements, but it was the value of the full dynamic list. So it was overriding the value obtained in the map. Simply changed the variable name to get around the override. Added a test scenario to ensure this never happens again.

### CODE REVIEW

File: packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js [hunk 1]
```diff
@@ -79,11 +79,11 @@ export class RepeatRenderManager {
 
     return (
       <>
-        {displayValues.map((value, index) =>
+        {displayValues.map((itemValue, itemIndex) =>
           <RepetitionScaffold
```
Comment (douglasbouttell-camunda) [inline packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js:83]: (nitpick, something to keep in mind for the future) 

I would have `{ ...restProps }` at the start do that it can't override any explicitly named props in future and help avoid this issue.

React will evaluate properties in order so you can define elements like so
```jsx
<SomeComponent
  overridableProperty={...}
  {...restProps}
  nonOverridableProperty={...}
/>

**Review by douglasbouttell-camunda — APPROVED** [review]
Took me a second to understand why this was broken. Good catch! Left you some advice for the future.
