### PR TITLE
fix(form-editor): clean up before import

### LINKED ISSUE #135: Command Stack Not Cleaned up When Importing Another Schema
__Describe the Bug__

There is no cleanup when importing a schema. Therefore, the command stack is not cleaned up. 🔥 

CodeSandbox: https://codesandbox.io/s/command-stack-not-cleaned-up-ibbxe?file=/src/index.js

__Steps to Reproduce__

1. Execute a command
2. Import another schema
3. Can still undo

__Expected Behavior__

Command stack is cleaned up.

__Environment__

- Library version: 0.2.4

### PR DESCRIPTION
**Pull request by philippfromme**
* fire <diagram.clear> and <form.clear> before import making sure the command stack is cleared
* fire <import.done> after import (necessary in the context of integrating v0.2.x into the Camunda Modeler)
* fire <diagram.destroy> to ensure diagram services like command stack are destroyed

Closes #135

### CODE REVIEW

File: packages/form-js-editor/src/FormEditor.js [hunk 1]
```diff
@@ -83,15 +83,23 @@ export default class FormEditor {
...
+    this.get('eventBus').fire('diagram.destroy');
+
     this._detach(false);
   }
 
   /**
    * @param {Schema} schema
    */
   importSchema(schema) {
+    this._emit('diagram.clear');
```
Comment (nikku) [inline packages/form-js-editor/src/FormEditor.js:100]: Can we move that to a separate `clear` API? That one could clear the registry, too (or the registry hooks up to the clear events, your choice).

File: packages/form-js-editor/src/FormEditor.js [hunk 2]
```diff
@@ -103,6 +111,8 @@ export default class FormEditor {
             schema
           });
 
+          this._emit('import.done', { warnings });
```
Comment (nikku) [inline packages/form-js-editor/src/FormEditor.js:114]: We do fire `import.done` no matter what, i.e. on error, too. Please implement (and test it) in form-js accordingly, too.

**Review by nikku — COMMENTED** [review]
Two comments.

File: packages/form-js-editor/src/FormEditor.js (hunk 1 above)
Comment (philippfromme) [reply packages/form-js-editor/src/FormEditor.js]: Done. 👍🏻

File: packages/form-js-editor/src/FormEditor.js (hunk 2 above)
Comment (philippfromme) [reply packages/form-js-editor/src/FormEditor.js:124]: Done. 👍🏻

File: packages/form-js-editor/src/FormEditor.js [hunk 3]
```diff
@@ -82,16 +82,34 @@ export default class FormEditor {
...
+    this.get('eventBus').fire('diagram.destroy');
+
     this._detach(false);
   }
 
   /**
    * @param {Schema} schema
    */
   importSchema(schema) {
+    this.clear();
```
Comment (nikku) [inline packages/form-js-editor/src/FormEditor.js:111]: Let's move this into the _promised_ land and we're good.

File: packages/form-js-viewer/src/Form.js [hunk 4]
```diff
@@ -100,6 +116,8 @@ export default class Form {
    * @param {Data} [data]
    */
   importSchema(schema, data = {}) {
+    this.clear();
```
Comment (nikku) [inline packages/form-js-viewer/src/Form.js:119]: Let's move this into the _promised_ land and we're good.

**Review by nikku — CHANGES_REQUESTED** [review]
Two small findings.

**Comment by philippfromme** [comment]
@nikku Done. Promises made, promises kept.

**Review by nikku — APPROVED** [review]
I'll have a lot of fun merging with my changes :tada:

**Comment by nikku** [comment]
General remark: Please use lower case for code comments.

I'm not aware that we changed that to upper cases within our team.

**Comment by nikku** [comment]
Exception: Articles, blogs, your own memoirs you inline via multi-line JSDoc statements:

```javascript
/**
 * Once upon a time I did set up to build this API. Now here it is. You won't guess what it does!
 * 
 * @param { any } something
 */
function once(something) { ... }
```
