### PR TITLE
fix: decimal values for min/max number validation

### LINKED ISSUE #497: `number` min/max validation only supports integer numbers
__Describe the Bug__

Currently, it is not possible to define a maximum value for a number field which isn't an integer. The code allows for it but the properties panel field does not. 

__Steps to Reproduce__

1. Create a `number` field
2. Set validation:max to 5.3
3. Check the schema, the value isn't serialized

__Expected Behavior__

Since we now support decimal numbers, we should also support decimal number validation

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #497

### CODE REVIEW

File: packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js [hunk 1]
```diff
@@ -235,6 +235,7 @@ function Min(props) {
     element: field,
     id,
     label: 'Minimum',
+    step: 'any',
```
Comment (vsgoulart) [inline packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js:238]: is this a standard config of the properties panel?

**Review by vsgoulart — APPROVED** [review]

File: packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js (hunk 1 above)
Comment (Skaiir) [reply packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js:238]: It's a standard config of number fields as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step. The properties panel components are pretty thin wrappers around the basic HTML components.
