### PR TITLE
fix: Prevent demo data from being created on edited tables

### LINKED ISSUE #997: Table component demo data is being added when importing an edited table
### Describe the Bug

When we added the table component we added feature of creating some initial table component, but with that we added the bug that creates this initial demo data on a table component that was edited via properties panel, we should avoid creating demo data on edited tables because we can't guarantee the table has compatible columns.

### Steps to Reproduce

1. Create a table, edit the `dataSource` via properties panel
2. Save this form schema
3. Reload the editor and import the saved schema
4. The initial demo data is created based on the `id` and not on the `dataSource`

### Expected Behavior

Create the initial demo data only if the `dataSource` has the same value as the `id` and only if the columns are compatible with the demo data

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by vsgoulart**
With the table component we added the concept of adding demo data to the new component, this data was being added when importing forms into the modeler.
This PR prevents this from happening and only adds the demo data when the schema matches with the demo data

Closes #997

- [ ] This PR adds a new `form-js` element or visually changes an existing component.
  * => In that case, we need to ensure we follow up on this, e.g. by [creating an issue in Tasklist](https://github.com/camunda/tasklist/issues/new/choose)

### CODE REVIEW

**Review by douglasbouttell-camunda — APPROVED** [review]

File: packages/form-js-viewer/src/render/components/form-fields/Table.js [hunk 1]
```diff
@@ -263,11 +265,30 @@ Table.config = {
...
-    { id: 1, name: 'John Doe', date: '31.01.2023' },
-    { id: 2, name: 'Erika Muller', date: '20.02.2023' },
-    { id: 3, name: 'Dominic Leaf', date: '11.03.2023' }
-  ],
+
+  /**
+   *
+   * @param {Field} field
+   */
+  generateInitialDemoData: (field) => {
```
Comment (Skaiir) [inline packages/form-js-viewer/src/render/components/form-fields/Table.js:273]: Generally, let's be careful with these kinds of changes. Our config object is tied in with the custom component framework and should be treated more or less as public API. Of course we're never obligated but changing how it's structured is something we should not do often. 

I don't think in this case it matters that much, because the whole initialDemoData stuff is a very unique definition here, but I'm concerned people will want to hook into this and we end up getting rid of it in the future.

Maybe it's worth annotating this as experimental, so that people seeing this implementation don't try to copy and rely on it.

Comment (Skaiir) [reply packages/form-js-viewer/src/render/components/form-fields/Table.js:273]: Or moving it to an experimental sub-object, which should get the point across 🤔

Comment (vsgoulart) [reply packages/form-js-viewer/src/render/components/form-fields/Table.js:275]: @Skaiir I added the `@experimental` tag
