### PR TITLE
fix: improve text prompts of empty group components

### LINKED ISSUE #965: Dynamic List - handle empty state better with resizing
### Describe the Bug

When resizing the dynamic list to be very little, the empty state starts looking very messy, we should find an alternative to this, either by hiding the state entirely or substituting it for a smaller, simpler text field (or even just an icon). 

grafik

### Steps to Reproduce

1. Add a dynamic list
2. Make it 2 columns wide
3. The placeholder text renders poorly

### Expected Behavior

- Update the placeholder text from "_Drag and drop components here to create a repeatable list item_" to "_**Drag and drop components here.**_":
  - The updated placeholder text to be shown for wider breakpoints.
  - No need to mention in the placeholder text that components will be repeated since there is a separate indicator below.
- When the width of the Dynamic list component is less than 150px then the placeholder text is not displayed.

### Context

- follow-up from https://github.com/bpmn-io/form-js/issues/796

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #965

@volodymyr-melnykc I made the hiding threshold 100pixels instead because it still seems to look okay, let me know how it seems to you. 

@vsgoulart Opted for a mutationobserver for simplicity, since this is purely a visual thing

### CODE REVIEW

File: packages/form-js-editor/src/render/components/FormEditor.js [hunk 1]
```diff
@@ -65,24 +65,57 @@ function ContextPad(props) {
...
+    return () => {
+      if (currentElement) {
+        resizeObserver.unobserve(currentElement);
+      }
+    };
+  }, []);
+
+  return (
+    <div class="fjs-empty-component" ref={ emptyComponentRef }>
+      <span style={ { display: isHidden ? 'none' : 'inline' } }>Drag and drop components here.</span>
```
Comment (vsgoulart) [inline packages/form-js-editor/src/render/components/FormEditor.js:94]: Let's use classes instead of inlining it

**Review by vsgoulart — CHANGES_REQUESTED** [review]
@Skaiir Even though this component won't `ResizeObserver` + refs are no that great for performance.

Let's try to use [container queries instead](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries) which allows use to avoid shipping more JS
